name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive] mlflow scikit-learn pandas

      - name: Write Google Drive Service Account Key
        # Write the service account JSON secret to a file for DVC to consume
        run: echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" > $HOME/gdrive-key.json

      - name: Configure DVC to use Google Drive service account
        run: |
          # Replace 'my-mlops-storage' with the actual name of your DVC remote
          dvc remote modify "https://drive.google.com/drive/folders/1pxPYOiWtIKNvGXKEf4rxdJjd8mD8sXx1" gdrive_use_service_account true
          dvc remote modify "https://drive.google.com/drive/folders/1pxPYOiWtIKNvGXKEf4rxdJjd8mD8sXx1" --local gdrive_service_account_json_file_path $HOME/gdrive-key.json

      - name: Pull data with DVC
        run: dvc pull

      - name: Run training script
        env:
          MLFLOW_TRACKING_URI: "file://$GITHUB_WORKSPACE/mlruns"
        run: python train_model.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
