name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas

      - name: Download dataset
        run: |
          mkdir -p data
          curl -L "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data" -o data/iris.csv
          echo "sepal_length,sepal_width,petal_length,petal_width,target" | cat - data/iris.csv > data/iris_with_headers.csv
          mv data/iris_with_headers.csv data/iris.csv

      - name: Run training script
        env:
          MLFLOW_TRACKING_URI: "file://$GITHUB_WORKSPACE/mlruns"
        run: python train_model.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/