name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive] mlflow scikit-learn pandas

      - name: Configure DVC headless authentication
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_AUTH_JSON: ${{ secrets.GDRIVE_AUTH_JSON }}
        run: |
          # Create the DVC config directory
          mkdir -p ~/.config/dvc
          # Write the auth JSON to a file that DVC can find
          echo "$GDRIVE_AUTH_JSON" > ~/.config/dvc/gdrive_user_credentials.json
          # Modify the remote to use the credentials and the folder ID
          dvc remote modify my-mlops-storage gdrive_client_id $GDRIVE_CLIENT_ID
          dvc remote modify my-mlops-storage gdrive_client_secret $GDRIVE_CLIENT_SECRET

      - name: Pull data with DVC
        run: |
          dvc pull

      - name: Run training script
        run: |
          # Set the MLflow tracking URI
          export MLFLOW_TRACKING_URI="file://$GITHUB_WORKSPACE/mlruns"
          python train_model.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/