name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive] mlflow scikit-learn pandas

      - name: Write Google Drive Service Account Key
        run: |
          cat <<EOF > $HOME/gdrive-key.json
${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
EOF

      - name: Debug service account JSON file
        run: head -20 $HOME/gdrive-key.json

      - name: Configure DVC to use Google Drive service account
        run: |
          dvc remote modify my-mlops-storage gdrive_use_service_account true
          dvc remote modify my-mlops-storage --local gdrive_service_account_json_file_path $HOME/gdrive-key.json

      - name: Pull data with DVC
        run: dvc pull

      - name: Run training script
        env:
          MLFLOW_TRACKING_URI: "file://$GITHUB_WORKSPACE/mlruns"
        run: python train_model.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
