name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive] mlflow scikit-learn pandas

      - name: Configure DVC remote and pull data
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
        run: |
          # Configure the DVC remote with the stored GitHub Secrets
          dvc remote modify my-mlops-storage gdrive_client_id $GDRIVE_CLIENT_ID
          dvc remote modify my-mlops-storage gdrive_client_secret $GDRIVE_CLIENT_SECRET
          # Use DVC to pull the data from Google Drive
          dvc pull

      - name: Run training script
        run: |
          # Set the MLflow tracking URI, which was our final fix
          export MLFLOW_TRACKING_URI="file://$GITHUB_WORKSPACE/mlruns"
          python train_model.py

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/